import {NgModule} from '@angular/core';
import {
    MatButtonModule, 
    MatCheckboxModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatDatepickerModule, 
    MatNativeDateModule, 
    MatCardModule,
    MatSidenavModule,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDividerModule,
    MatDialogModule,
   } from '@angular/material';

@NgModule({
  imports: [
      MatButtonModule, 
      MatCheckboxModule, 
      MatFormFieldModule, 
      MatInputModule, 
      MatDatepickerModule, 
      MatNativeDateModule, 
      MatCardModule, 
      MatSidenavModule,
      MatToolbarModule,
      MatIconModule,
      MatListModule,
      MatTabsModule,
      MatSelectModule,
      MatProgressSpinnerModule,
      MatDividerModule,
      MatDialogModule,
    ],
  exports: [
      MatButtonModule, 
      MatCheckboxModule, 
      MatFormFieldModule, 
      MatInputModule, 
      MatDatepickerModule, 
      MatNativeDateModule, 
      MatCardModule, 
      MatSidenavModule,
      MatToolbarModule,
      MatIconModule,
      MatListModule,
      MatTabsModule,
      MatSelectModule,
      MatProgressSpinnerModule,
      MatDividerModule,
      MatDialogModule,
    ],
})
export class MaterialModule { }
